<html>
    <body>
        <h1>This is index.php</h1>
        <p>The following is generated by PHP:</p>
        <!-- the following is a PHP script-->
        <?php
            // print hello world
            echo("Hello world!")
        ?>
        <h2>Static files</h2>
        <!-- the following shows static usage inside of the container -->
        <p>
            <div style="width: 256px;">
                <img src="img/marie.png" alt="Marie the cat">
            </div>
            The cat Marie.
        </p>
        <h2>PHP Info</h2>
        <p>
            <!-- Another PHP script is used to display phpinfo-->
            <?php
                // print php info
                phpinfo(INFO_ALL)
            ?>
        </p>
    </body>
</html>


