# specify the node base image with your desired version node:<version>
FROM node:alpine
# replace this with your application's default port
EXPOSE 8888

WORKDIR /usr/src/app

COPY server.js /usr/src/app
COPY client.js /usr/src/app
